<?php

namespace Proxies\__CG__\Core\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \Core\UserBundle\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'id', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'nome', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'email', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'senha', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'cpf', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'dtNascimento', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'sexo', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'rg', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'emissor', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'dtCadastro', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'tipoUser', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'flActive', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'flAdmin', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'flAssociado', 'descontoPessoaJuridica', 'descontoPessoaFisica');
        }

        return array('__isInitialized__', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'id', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'nome', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'email', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'senha', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'cpf', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'dtNascimento', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'sexo', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'rg', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'emissor', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'dtCadastro', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'tipoUser', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'flActive', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'flAdmin', '' . "\0" . 'Core\\UserBundle\\Entity\\User' . "\0" . 'flAssociado', 'descontoPessoaJuridica', 'descontoPessoaFisica');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenha($senha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenha', array($senha));

        return parent::setSenha($senha);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenha', array());

        return parent::getSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpf($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpf', array($value));

        return parent::setCpf($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpf', array());

        return parent::getCpf();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtNascimento($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtNascimento', array($value));

        return parent::setDtNascimento($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtNascimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtNascimento', array());

        return parent::getDtNascimento();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexo($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexo', array($value));

        return parent::setSexo($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexo', array());

        return parent::getSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setRg($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRg', array($value));

        return parent::setRg($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getRg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRg', array());

        return parent::getRg();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmissor($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmissor', array($value));

        return parent::setEmissor($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmissor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmissor', array());

        return parent::getEmissor();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtCadastro($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtCadastro', array($value));

        return parent::setDtCadastro($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtCadastro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtCadastro', array());

        return parent::getDtCadastro();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoUser($tipoUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoUser', array($tipoUser));

        return parent::setTipoUser($tipoUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoUser', array());

        return parent::getTipoUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescontoPessoaFisica($descontoPessoaFisica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescontoPessoaFisica', array($descontoPessoaFisica));

        return parent::setDescontoPessoaFisica($descontoPessoaFisica);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescontoPessoaFisica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescontoPessoaFisica', array());

        return parent::getDescontoPessoaFisica();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescontoPessoaJuridica($descontoPessoaJuridica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescontoPessoaJuridica', array($descontoPessoaJuridica));

        return parent::setDescontoPessoaJuridica($descontoPessoaJuridica);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescontoPessoaJuridica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescontoPessoaJuridica', array());

        return parent::getDescontoPessoaJuridica();
    }

    /**
     * {@inheritDoc}
     */
    public function setFlActive($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlActive', array($value));

        return parent::setFlActive($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getFlActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFlActive', array());

        return parent::getFlActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setFlAdmin($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlAdmin', array($value));

        return parent::setFlAdmin($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getFlAdmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFlAdmin', array());

        return parent::getFlAdmin();
    }

    /**
     * {@inheritDoc}
     */
    public function setFlAssociado($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlAssociado', array($value));

        return parent::setFlAssociado($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getFlAssociado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFlAssociado', array());

        return parent::getFlAssociado();
    }

    /**
     * {@inheritDoc}
     */
    public function setData($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', array($data));

        return parent::setData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function toJson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toJson', array());

        return parent::toJson();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
