<?php

namespace Proxies\__CG__\Evento\EventoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evento extends \Evento\EventoBundle\Entity\Evento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'id', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'titulo', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'descricao', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'inscricaoInicio', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'inscricaoFim', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'dataInicio', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'dataFim', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'local', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'cargaHoraria', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'dataCadastro', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'publicar', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'valorSocio', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'valorNSocio', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'valorEstudante', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'valorEstudanteAssociado', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'eventoPago', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'ativo', 'descontos');
        }

        return array('__isInitialized__', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'id', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'titulo', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'descricao', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'inscricaoInicio', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'inscricaoFim', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'dataInicio', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'dataFim', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'local', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'cargaHoraria', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'dataCadastro', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'publicar', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'valorSocio', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'valorNSocio', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'valorEstudante', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'valorEstudanteAssociado', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'eventoPago', '' . "\0" . 'Evento\\EventoBundle\\Entity\\Evento' . "\0" . 'ativo', 'descontos');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Evento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescontos($descontos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescontos', array($descontos));

        return parent::setDescontos($descontos);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', array($titulo));

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', array());

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescricao($descricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescricao', array($descricao));

        return parent::setDescricao($descricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescricao', array());

        return parent::getDescricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setInscricaoInicio($inscricaoInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInscricaoInicio', array($inscricaoInicio));

        return parent::setInscricaoInicio($inscricaoInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getInscricaoInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscricaoInicio', array());

        return parent::getInscricaoInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setInscricaoFim($inscricaoFim)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInscricaoFim', array($inscricaoFim));

        return parent::setInscricaoFim($inscricaoFim);
    }

    /**
     * {@inheritDoc}
     */
    public function getInscricaoFim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscricaoFim', array());

        return parent::getInscricaoFim();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataInicio($dataInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataInicio', array($dataInicio));

        return parent::setDataInicio($dataInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataInicio', array());

        return parent::getDataInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataFim($dataFim)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataFim', array($dataFim));

        return parent::setDataFim($dataFim);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataFim()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataFim', array());

        return parent::getDataFim();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocal($local)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocal', array($local));

        return parent::setLocal($local);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocal', array());

        return parent::getLocal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCargaHoraria($cargaHoraria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCargaHoraria', array($cargaHoraria));

        return parent::setCargaHoraria($cargaHoraria);
    }

    /**
     * {@inheritDoc}
     */
    public function getCargaHoraria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCargaHoraria', array());

        return parent::getCargaHoraria();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataCadastro($dataCadastro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataCadastro', array($dataCadastro));

        return parent::setDataCadastro($dataCadastro);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataCadastro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataCadastro', array());

        return parent::getDataCadastro();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublicar($publicar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublicar', array($publicar));

        return parent::setPublicar($publicar);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublicar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublicar', array());

        return parent::getPublicar();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorSocio($valorSocio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorSocio', array($valorSocio));

        return parent::setValorSocio($valorSocio);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorSocio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorSocio', array());

        return parent::getValorSocio();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorNSocio($valorNSocio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorNSocio', array($valorNSocio));

        return parent::setValorNSocio($valorNSocio);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorNSocio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorNSocio', array());

        return parent::getValorNSocio();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorEstudante($valorEstudante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorEstudante', array($valorEstudante));

        return parent::setValorEstudante($valorEstudante);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorEstudante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorEstudante', array());

        return parent::getValorEstudante();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorEstudanteAssociado($valorEstudanteAssociado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorEstudanteAssociado', array($valorEstudanteAssociado));

        return parent::setValorEstudanteAssociado($valorEstudanteAssociado);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorEstudanteAssociado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorEstudanteAssociado', array());

        return parent::getValorEstudanteAssociado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventoPago($eventoPago)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventoPago', array($eventoPago));

        return parent::setEventoPago($eventoPago);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventoPago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventoPago', array());

        return parent::getEventoPago();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtivo($ativo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtivo', array($ativo));

        return parent::setAtivo($ativo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtivo', array());

        return parent::getAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setData($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', array($data));

        return parent::setData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function toJson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toJson', array());

        return parent::toJson();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
